
export const FETCH_MEMBER = 'FETCH_MEMBER';
export const TOGGLE_MEMBER_SIDEBAR = 'TOGGLE_MEMBER_SIDEBAR';
export const FETCH_MEMBER_BY_QUERY = 'FETCH_MEMBER_BY_QUERY';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const FETCH_MEMBER_BY_ID = 'FETCH_MEMBER_BY_ID';
export const FILL_MEMBER_BY_DDL = 'FILL_MEMBER_BY_DDL';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const UPDATE_MEMBER_FROM_TASK = 'UPDATE_MEMBER_FROM_TASK';
export const UPDATE_MEMBER_TASK_EDIT_FORM = 'UPDATE_MEMBER_TASK_EDIT_FORM';
export const DELETE_MEMBER_BY_RANGE = 'DELETE_MEMBER_BY_RANGE';
export const FETCH_MEMBER_DETAILS = 'FETCH_MEMBER_DETAILS';
export const LOADING = 'LOADING';
